### ISSUE TITLE
Improved conda-build linking phase in conda-build 3.1.3

### ISSUE THREAD

**Issue by msarahan** [conda-forge/trilinos-feedstock#10]
Just a heads-up, as I know you've had issues with the "fixing linking" time in conda-build.  This PR just went in: https://github.com/conda/conda-build/pull/2564

It very dramatically improves this issue.  This will be in conda-build 3.1.3.  Conda-forge is not quite using conda-build 3 yet - that was last discussed in our meeting on Monday.  Agenda/notes are at https://paper.dropbox.com/doc/Compilers-conda-build-3-update-20171211-JSvRO2Lk2Z7Bbf2zDaG9p

**Comment by isuruf** [comment]
Thanks @msarahan. This should also enable `sagelib` which had hundreds of dylibs.

**Comment by isuruf** [comment]
Works great.
