### ISSUE TITLE
build on windows

### ISSUE THREAD

**Issue by looooo** [conda-forge/trilinos-feedstock#11]
What is missing to enable windows builds?
- openmpi ? would it be possible to build without mpi?
- openblas: https://anaconda.org/conda-forge/openblas/files

**Comment by wfspotz** [comment]
Trilinos is designed to be optionally built without MPI. In the context of an Anaconda package, we would probably want an independent package such as `trilinos-serial`.

**Comment by wfspotz** [comment]
@ocefpaf I have been wondering about a serial version of `trilinos`. Trilinos con be configured with MPI turned off. How would we do this? Could `none` be one of the mpi variants? Seems unlikely to work, even if `none` is a valid option. Would we need a completely different `trilinos-serial` package? How could we make it exclusive to the `trilinos` package? Thx

**Comment by ocefpaf** [comment]
> @ocefpaf I have been wondering about a serial version of trilinos. Trilinos con be configured with MPI turned off. How would we do this?

I don't know how to do that b/c I'm not a `trilinos` user, sorry.

> Could `none` be one of the mpi variants?

It should be an option if that is not possible already. Pinging @minrk who may have already thought about this.

**Comment by minrk** [comment]
actually-none `null` seems to be scrubbed from the matrix by conda-build, so I've been using the string "nompi" e.g. [in hdf5](https://github.com/conda-forge/hdf5-feedstock/pull/90). If you want to have a 'default' install, then the gist is to have a track_features for `trilinos_mpich` or `trilinos_nompi` for only the non-preferred variants.
