### ISSUE TITLE
Recipe is in `recipe/recipe/` instead of `recipe/`

### ISSUE THREAD

**Issue by isuruf** [conda-forge/trilinos-feedstock#5]
~This might be the cause of https://github.com/conda-forge/trilinos-feedstock/issues/1~
Ignore above

**Comment by wfspotz** [comment]
@isuruf Does this still need to be fixed? If not, why not?

**Comment by isuruf** [comment]
It still needs to be fixed. It doesn't matter for the building, but might be an issue for bots doing maintenance.
